# Generated by Django 5.1.1 on 2024-10-22 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.TextField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.IntegerField()),
                ('kilometraje', models.IntegerField()),
                ('tipo_combustible', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Automovil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cuentas.usuario')),
                ('id_especificaciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automoviles.especificaciones')),
            ],
        ),
    ]
