# Generated by Django 5.1.1 on 2024-10-22 16:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_taller', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('imagen', models.TextField(default='https://images.pexels.com/photos/1699104/pexels-photo-1699104.png?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200')),
                ('monto', models.FloatField(default=0)),
                ('descripcion', models.TextField(default='El mejor arreglo')),
                ('id_taller', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='servicio.taller')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('anio', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('descripcion', models.TextField()),
                ('id_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.servicio')),
                ('id_taller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.taller')),
            ],
        ),
    ]
