# Generated by Django 5.1.1 on 2024-10-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='imagen',
            field=models.TextField(default='https://images.pexels.com/photos/1699104/pexels-photo-1699104.png?auto=compress&cs=tinysrgb&fit=crop&h=627&w=1200'),
        ),
    ]
