# Generated by Django 5.1.1 on 2024-10-08 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_servicio_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='id_taller',
        ),
    ]
