# Generated by Django 5.1.1 on 2024-10-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0004_remove_taller_id_servicio_servicio_id_taller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='fecha_fin_Mantenimiento',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='fecha_inicio_mantenimiento',
        ),
        migrations.AddField(
            model_name='servicio',
            name='monto',
            field=models.FloatField(default=0),
        ),
    ]
