# Generated by Django 5.1.1 on 2024-10-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0006_servicio_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='id_automovil',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='anio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='marca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
