# Generated by Django 5.1.1 on 2024-10-17 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0007_remove_mantenimiento_id_automovil_mantenimiento_anio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='nombre_taller',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='id_taller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='servicio.taller'),
            preserve_default=False,
        ),
    ]
