# Generated by Django 5.1.1 on 2024-10-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0008_remove_mantenimiento_nombre_taller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='anio',
            field=models.DateTimeField(default=2000, unique_for_year=True),
            preserve_default=False,
        ),
    ]
