# Generated by Django 5.1.1 on 2024-10-17 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0010_alter_mantenimiento_anio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='anio',
        ),
    ]
