# Generated by Django 5.1.1 on 2024-10-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0011_remove_mantenimiento_anio'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='anio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
