# Generated by Django 5.1.1 on 2024-10-22 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0014_alter_mantenimiento_anio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mantenimiento',
            old_name='anio',
            new_name='fecha',
        ),
    ]
