# Generated by Django 5.1.1 on 2024-10-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0015_rename_anio_mantenimiento_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='fecha',
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='anio',
            field=models.DateField(default='2024-10-22'),
            preserve_default=False,
        ),
    ]
