# Generated by Django 5.1.1 on 2024-10-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0016_remove_mantenimiento_fecha_mantenimiento_anio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='anio',
            field=models.DateTimeField(),
        ),
    ]
