# Generated by Django 5.1.1 on 2024-10-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0017_alter_mantenimiento_anio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='anio',
            field=models.CharField(max_length=100),
        ),
    ]
