# Generated by Django 5.1.1 on 2024-10-22 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0018_alter_mantenimiento_anio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='anio',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
